/*
 TO BE OPTIMIZED BECAUSE NOW SHE WILL ALSO GET THE RESULT OF BOOK THAT ARE ALREADY IN SHELF (ADD CHECK IF BOOK WAS LOANED YESTERDAY)
 
	STRAIGHT FORWARD NO NEED FOR ANYTHING

*/

/*DROP FUNCTION IF EXISTS dbo.loaned_books_to_put_on_shelf*/

GO
CREATE FUNCTION dbo.loaned_books_to_put_on_shelf(@BranchID uniqueidentifier)
RETURNS TABLE
	AS
		
		RETURN (SELECT BookItemID FROM Loan WHERE BranchID = @BranchID AND LoanPickupDate IS NULL  )

	GO
